version: '3.8'
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb_container
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
      MONGO_INITDB_DATABASE: muses
    volumes:
      - ../dbs/muses:/data/db
      - ../dbs/muses/logs:/var/log/mongodb/
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - 27018:27017
  
  postgresql:
    image: postgres:latest
    restart: always
    container_name: postgresql_container
    hostname: host-postgresql
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: hades
    volumes:
      - ../dbs/hades:/var/lib/postgresql
    ports:
      - 5433:5432