export const ACTION_REPOSITORY = Symbol('ACTION_REPOSITORY');
export const ACTION_CATALOG_REPOSITORY = Symbol('ACTION_CATALOG_REPOSITORY');
export const MODULE_FACADE = Symbol('MODULE_FACADE');
export const SUB_MODULE_FACADE = Symbol('SUB_MODULE_FACADE');
export const RESOURCE_FACADE = Symbol('RESOURCE_FACADE');

export const HADES_SERVER_CONNECTION_PROXY_NAME = Symbol(process.env.HADES_SERVER_RABBIT_MQ_PROXY_NAME);