export const PROJECT_REPOSITORY = Symbol('PROJECT_REPOSITORY');
export const ECOSYSTEM_MODULE_FACADE = Symbol('ECOSYSTEM_MODULE_FACADE');
export const MODULE_MODULE_FACADE = Symbol('MODULE_MODULE_FACADE');
