export const MODULE_REPOSITORY = Symbol('MODULE_REPOSITORY');
export const PROJECT_MODULE_FACADE = Symbol('PROJECT_MODULE_FACADE');
export const SUB_MODULE_MODULE_FACADE = Symbol('SUB_MODULE_MODULE_FACADE');
